version: '3.8'

services:
    redis:
        image: redis:latest
    
    example-frontend: 
        build:
            dockerfile: Dockerfile.frontend
        ports: 
            - 5000:5000
        restart: unless-stopped

    example-backend:
        build:
            dockerfile: Dockerfile.backend
        ports:
            - 8080:8080
        restart: unless-stopped
    