version: '3.8'

services:

    example-frontend: 
        build:
            dockerfile: Dockerfile.frontend
        ports:
            - 5000:5000

    example-backend:
        build:
            dockerfile: Dockerfile.backend
        ports:
            - 8080:8080
