FROM alpine:3.16 as build-stage

RUN apk update && apk add alpine-sdk libressl-dev && rm -rf /var/cache/apk*
RUN git clone git://r-36.net/geomyidae
RUN make -C /geomyidae
RUN make -C /geomyidae install

FROM alpine:3.16
RUN apk update && apk add --no-cache libressl-dev
WORKDIR /app
RUN adduser -D appuser && mkdir -p /var/gopher && mkdir -p /var/gopher/inception
COPY inception.pdf /var/gopher/inception
COPY welcome.txt /var/gopher/welcome.txt
COPY index.gph /var/gopher/index.gph
COPY --from=build-stage /geomyidae/geomyidae ./geomyidae
RUN chown appuser /app/geomyidae /var/gopher /var/gopher/inception
USER appuser
EXPOSE 70
CMD ./geomyidae -d -b /var/gopher -p 70 -h mtrietz.42.fr