FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./example-frontend/ .

RUN npm install && npm run build && npm install -g serve && adduser -D appuser

USER appuser

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]
