FROM node:16-alpine AS build-stage
WORKDIR /usr/src/app

COPY ./example-frontend/ .

RUN npm install && npm run build 

FROM node:16-alpine

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/build ./build

RUN adduser -D appuser && npm install -g serve

USER appuser

EXPOSE 5000

CMD ["serve", "-n", "-s", "-l", "5000", "build"]