FROM node:16

WORKDIR /usr/src/app

COPY material-applications/example-frontend .

RUN npm install

ENV REACT_APP_BACKEND_URL http://localhost/api/

RUN npm run build

RUN npm install -g serve

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]
